site_name: pasqal-cloud
site_url: https://pasqal-io.github.io/pasqal-cloud/
repo_url: https://github.com/pasqal-io/pasqal-cloud
repo_name: pasqal-io/pasqal-cloud
edit_uri: edit/main/docs/

theme:
  name: "material"
  features:
    - navigation.tabs
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Advanced Usage:
      - advanced-usage/authentication.md
      - Target different regions and environments: advanced-usage/target-different-regions-and-environments.md
      - Use PasqalCloudClient: advanced-usage/use-cloud-client.md

  - API reference:
      - Overview: reference/index.md
      - PasqalCloudConnection: reference/pasqal_cloud_connection.md
      - OVHConnection: reference/ovh_connection.md
      - Backends: reference/backends.md
      - PasqalCloudClient: reference/pasqal_cloud_client.md

  - Migrating from pulser-pasqal: migrating-from-pulser-pasqal.md

plugins:
  - mkdocstrings:
      # same config as Qadence
      default_handler: python
      handlers:
        python:
          path: [pasqal-cloud]
          options:
            show_root_toc_entry: false
            heading_level: 3
            merge_init_into_class: true
            docstring_section_style: spacy
            members_order: source
            filters:
              - "!^_" # exlude all members starting with _
              - "^__init__$" # but always include __init__ modules and methods
              - "^__new__$" # but always include __new__ methods

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: "!!python/name:markdown_exec.validator"
          format: "!!python/name:markdown_exec.formatter"
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true

extra_css:
  # from Qadence, to get paddings on blocks
  - extras/css/mkdocstrings.css
