[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

dependencies = [
    "auth0-python >= 3.23.1, <4.0.0",
    "requests>=2.25.1, <3.0.0",
    "pyjwt[crypto]>=2.5.0, <3.0.0",
    "pydantic >= 2.6.0, <3.0.0",
    "requests-mock==1.12.1",
]
