name: Publish MkDocs documentation to gh-pages
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Verify tag matches VERSION.txt
        run: |
          # strips refs/tags/ prefix from GITHUB_REF
          tag="${GITHUB_REF#refs/tags/}"
          version=$(cat VERSION.txt)
          if [ "$tag" != "$version" ]; then
            echo "Tag '$tag' does not match VERSION.txt '$version'"
            exit 1
          fi
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> "$GITHUB_ENV"
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: doc-publish-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            doc-publish-
      - run: pip install .[docs]
        working-directory: pasqal-cloud
      - run: mkdocs gh-deploy --force
