name: Lint
on: pull_request

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
