name: Test release notes to delete before merge
on: push

jobs:
  display-github-release-notes:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract version from _version.py
        id: get_version
        run: |
          version=$(python -c "exec(open('pasqal_cloud/_version.py').read()); print(__version__)")
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Debug CHANGELOG.md
        run: cat CHANGELOG.md

      - name: Get release notes from CHANGELOG.md
        run: |
          version=${{ env.VERSION }}
          # Extract notes from changelog
          notes=$(awk -v ver="$version" '
              BEGIN { found_version=0; leading_blank=1; }
              /## \[/ { if (found_version) { exit } }
              /## \['"$version"'\]/ {
                  found_version=1;
                  next
              }
              found_version {
                  # Remove the _released line
                  if ($0 ~ /^_released/) { next }

                  # Remove leading ### or ## or # and any additional whitespace
                  gsub(/^#+ +/, "", $0);

                  # Check if the line is blank
                  if ($0 != "") {
                      print $0;  # Print the current line
                      leading_blank=0;  # Reset leading blank flag
                  } else if (!leading_blank) {
                      print "";  # Print a blank line for subsequent empty lines
                  }
              }
          ' CHANGELOG.md)
          echo "Extracted notes: $notes"
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$notes" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Display release notes
        run: echo "${{ env.RELEASE_NOTES }}"
